name: teamshare
description: "team share"

publish_to: 'none'
private: true

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  file_picker: ^10.2.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.3
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/missing.jpg
    - assets/images/TEAM.png
    - assets/images/TEAM-2.png
    - assets/images/TEAM-3.png
    - assets/images/TEAM-4.png
    - assets/images/TEAM-5.png
    - assets/images/TEAM-6.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf5
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
